device: /dev/ttyACM0
frame_id: gps
uart1:
  baudrate: 38400
config_on_startup: false

# Enable AGPS and settings
agps: 
  enable: true
  token: noToken                   # Token to request the agps file 
  path: /data                      # path to store the agps file 
  